### ISSUE TITLE
Hi and Thanks for this fork of avatar image, how can i compile it?

### ISSUE THREAD

**Issue by Killuacrow** [Quackster/HabboImager#1]
Hi Quackster, how can i compile it to use? and it depend on arcturus database connection or not? Thanks in advance, i hope in a your reply

**Comment by Quackster** [comment]
You compile it by importing as a Gradle project in IntelliJ

>and it depend on arcturus database connection or not

It does, for badges. I think.

**Comment by Killuacrow** [comment]
Thanks for the reply
i have this problem
Error: LinkageError occurred while loading main class wf.arcturus.Imaging
        java.lang.UnsupportedClassVersionError: wf/arcturus/Imaging has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0
i changed too many times jdk version..
http://prntscr.com/nn650g
i tried all this version 
http://prntscr.com/nn659n
but with the 12 i can build but i have problem with version when is start the jar
with other version i have problem with compiling..

**Comment by Quackster** [comment]
Create a png image called default in /resources/ folder and connect your imager to your Arcturus database.

**Comment by Killuacrow** [comment]
Thanks very much!  But why i have this problem?
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_circles_2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ornament_1_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ornament_1_part1.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ornament_2_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ornament_2_part1.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_misc_1_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_misc_1_part1.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_misc_2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_beams_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_beams_part1.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ring.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_simplestar_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_simplestar_part1.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_spiral.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_book.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_egg.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_ornament.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_shield_part2.png
[Badge Imager] Missing Badge Part: resources/badge//badgepart_base_shield_part1.png

**Comment by Quackster** [comment]
You're missing badges I guess. You need the files from the original release.
